// export const projects = [
//     {
//       id: 1,
//       image: "/assets/img/project/05.jpg",
//       category: "Product Design",
//       title: "Business Task Management Dashboard Design",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//             "/assets/img/project/002.png",
//             "/assets/img/project/001.JPG",
//           "/assets/img/project/003.png",
//           "/assets/img/project/004.png",
//           "/assets/img/project/005.png",
//           "/assets/img/project/006.png",
//           "/assets/img/project/007.jpg",
//           "/assets/img/project/008.JPG",
//           "/assets/img/project/009.jpg",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//     {
//       id: 2,
//       image: "/assets/img/project/06.jpg",
//       category: "Website Design",
//       title: "Business Consulting Web Explorations Design",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//             "/assets/img/project/003.png",
//           "/assets/img/project/001.JPG",
//           "/assets/img/project/002.png",
//           "/assets/img/project/004.png",
//           "/assets/img/project/005.png",
//           "/assets/img/project/006.png",
//           "/assets/img/project/007.jpg",
//           "/assets/img/project/008.JPG",
//           "/assets/img/project/009.jpg",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//     {
//       id: 3,
//       image: "/assets/img/project/07.jpg",
//       category: "Product Design",
//       title: "Mobile Applications Design",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//             "/assets/img/project/004.png",
//           "/assets/img/project/001.JPG",
//           "/assets/img/project/002.png",
//           "/assets/img/project/003.png",
//           "/assets/img/project/005.png",
//           "/assets/img/project/006.png",
//           "/assets/img/project/007.jpg",
//           "/assets/img/project/008.JPG",
//           "/assets/img/project/009.jpg",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//     {
//       id: 4,
//       image: "/assets/img/project/08.jpg",
//       category: "Website Design",
//       title: "Furniture Website Design",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//             "/assets/img/project/005.png",
//           "/assets/img/project/001.JPG",
//           "/assets/img/project/002.png",
//           "/assets/img/project/003.png",
//           "/assets/img/project/004.png",
//           "/assets/img/project/006.png",
//           "/assets/img/project/007.jpg",
//           "/assets/img/project/008.JPG",
//           "/assets/img/project/009.jpg",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//     {
//       id: 5,
//       image: "/assets/img/project/09.jpg",
//       category: "Product Design",
//       title: "Business Card Design and Branding Identity",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//             "/assets/img/project/006.png",
//           "/assets/img/project/001.JPG",
//           "/assets/img/project/002.png",
//           "/assets/img/project/003.png",
//           "/assets/img/project/004.png",
//           "/assets/img/project/005.png",
//           "/assets/img/project/007.jpg",
//           "/assets/img/project/008.JPG",
//           "/assets/img/project/009.jpg",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//     {
//       id: 6,
//       image: "/assets/img/project/10.jpg",
//       category: "Website Design",
//       title: "Modern T-Shirt Design and Branding Identity",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//             "/assets/img/project/007.jpg",
//           "/assets/img/project/001.JPG",
//           "/assets/img/project/002.png",
//           "/assets/img/project/003.png",
//           "/assets/img/project/004.png",
//           "/assets/img/project/005.png",
//           "/assets/img/project/006.png",
//           "/assets/img/project/008.JPG",
//           "/assets/img/project/009.jpg",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//     {
//       id: 7,
//       image: "/assets/img/project/11.jpg",
//       category: "Product Design",
//       title: "Mobile Applications Design",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//             "/assets/img/project/008.JPG",
//           "/assets/img/project/001.JPG",
//           "/assets/img/project/002.png",
//           "/assets/img/project/003.png",
//           "/assets/img/project/004.png",
//           "/assets/img/project/005.png",
//           "/assets/img/project/006.png",
//           "/assets/img/project/007.jpg",
//           "/assets/img/project/009.jpg",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//     {
//       id: 8,
//       image: "/assets/img/project/12.jpg",
//       category: "Product Design",
//       title: "Furniture Website Design",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//             "/assets/img/project/009.jpg",
//           "/assets/img/project/001.JPG",
//           "/assets/img/project/002.png",
//           "/assets/img/project/003.png",
//           "/assets/img/project/004.png",
//           "/assets/img/project/005.png",
//           "/assets/img/project/006.png",
//           "/assets/img/project/007.jpg",
//           "/assets/img/project/008.JPG",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//     {
//       id: 9,
//       image: "/assets/img/project/12.jpg",
//       category: "Product Design",
//       title: "Furniture Website Design",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//          "/assets/img/project/001.JPG",
//           "/assets/img/project/002.png",
//           "/assets/img/project/003.png",
//           "/assets/img/project/004.png",
//           "/assets/img/project/005.png",
//           "/assets/img/project/006.png",
//           "/assets/img/project/007.jpg",
//           "/assets/img/project/008.JPG",
//           "/assets/img/project/009.jpg",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//     {
//       id: 10,
//       image: "/assets/img/project/12.jpg",
//       category: "Product Design",
//       title: "Furniture Website Design",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//             "/assets/img/project/002.png",
//           "/assets/img/project/001.JPG",
//           "/assets/img/project/003.png",
//           "/assets/img/project/004.png",
//           "/assets/img/project/005.png",
//           "/assets/img/project/006.png",
//           "/assets/img/project/007.jpg",
//           "/assets/img/project/008.JPG",
//           "/assets/img/project/009.jpg",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//     {
//       id: 11,
//       image: "/assets/img/project/12.jpg",
//       category: "Product Design",
//       title: "Furniture Website Design",
//       link: "project-details",
//       description: "Designing a dashboard for task management.",
//       details: {
//         images: [
//             "/assets/img/project/003.png",
//           "/assets/img/project/001.JPG",
//           "/assets/img/project/002.png",
//           "/assets/img/project/004.png",
//           "/assets/img/project/005.png",
//           "/assets/img/project/006.png",
//           "/assets/img/project/007.jpg",
//           "/assets/img/project/008.JPG",
//           "/assets/img/project/009.jpg",
//         ],
//         overview: "Introduction Of Projects Overview",
//         content: "Designing a digital product and branding project involves several key steps...",
//         information: {
//           client: "Myron S.",
//           category: "Design & Dev",
//           date: "October, 2024",
//           location: "New York",
//           duration: "1 month",
//         },
//       },
//     },
//   ];

  export const projects = [
    {
      id: 1,
      image: "/assets/img/services/industrial-electricity.jpg",
      category: "Industrial Electricity & Automation",
      title: "Electrical Systems Design & Installation",
      link: "industrial-electricity",
      description: "Design and installation of electrical systems for industrial and commercial applications.",
      details: {
        images: [
            "/assets/img/project/001.JPG",
                "/assets/img/project/002.png",
                "/assets/img/project/003.png",
                "/assets/img/project/004.png",
                "/assets/img/project/005.png",
                "/assets/img/project/006.png",
                "/assets/img/project/007.jpg",
                "/assets/img/project/008.JPG",
                "/assets/img/project/009.jpg",
                ],
        overview: "Introduction to Industrial Electricity & Automation Services",
        content: "We provide comprehensive solutions for industrial electricity and automation, including the design and implementation of electrical systems, control panels, and industrial instrumentation.",
        information: {
          client: "Industrial Clients",
          category: "Electricity & Automation",
          date: "Ongoing",
          location: "Morocco",
          duration: "Varies by project",
        },
      },
    },
    {
      id: 2,
      image: "/assets/img/services/access-control.jpg",
      category: "Security Systems",
      title: "Access Control & Evacuation Systems",
      link: "access-control",
      description: "Installation and configuration of access control and emergency evacuation systems.",
      details: {
        images: [
            "/assets/img/project/002.png",
            "/assets/img/project/001.JPG",
                "/assets/img/project/003.png",
                "/assets/img/project/004.png",
                "/assets/img/project/005.png",
                "/assets/img/project/006.png",
                "/assets/img/project/007.jpg",
                "/assets/img/project/008.JPG",
                "/assets/img/project/009.jpg",
        ],
        overview: "Introduction to Access Control & Evacuation Systems",
        content: "We offer advanced access control solutions, including biometric readers, centralized emergency exit management, and secure access mechanisms.",
        information: {
          client: "Commercial & Residential Clients",
          category: "Security Systems",
          date: "Ongoing",
          location: "Morocco",
          duration: "Varies by project",
        },
      },
    },
    {
      id: 3,
      image: "/assets/img/services/fire-detection.jpg",
      category: "Security Systems",
      title: "Fire & Intrusion Detection Systems",
      link: "fire-detection",
      description: "Installation of fire and intrusion detection systems to protect your property.",
      details: {
        images: [
            "/assets/img/project/003.png",
          "/assets/img/project/002.png",
                "/assets/img/project/001.JPG",
                "/assets/img/project/004.png",
                "/assets/img/project/005.png",
                "/assets/img/project/006.png",
                "/assets/img/project/007.jpg",
                "/assets/img/project/008.JPG",
                "/assets/img/project/009.jpg",
        ],
        overview: "Introduction to Fire & Intrusion Detection Systems",
        content: "Our fire and intrusion detection systems ensure the safety and security of your premises with advanced alarm systems and supervision software.",
        information: {
          client: "Commercial & Residential Clients",
          category: "Security Systems",
          date: "Ongoing",
          location: "Morocco",
          duration: "Varies by project",
        },
      },
    },
    {
      id: 4,
      image: "/assets/img/services/it-cabling.jpg",
      category: "IT & Network Solutions",
      title: "IT Cabling & Video Surveillance",
      link: "it-cabling",
      description: "Professional IT cabling and video surveillance installation services.",
      details: {
        images: [
            "/assets/img/project/004.png",
          "/assets/img/project/002.png",
                "/assets/img/project/001.JPG",
                "/assets/img/project/003.png",
                "/assets/img/project/005.png",
                "/assets/img/project/006.png",
                "/assets/img/project/007.jpg",
                "/assets/img/project/008.JPG",
                "/assets/img/project/009.jpg",
        ],
        overview: "Introduction to IT Cabling & Video Surveillance Services",
        content: "We provide high-quality IT cabling and video surveillance solutions, including the installation of network infrastructure and IP/analog cameras.",
        information: {
          client: "Commercial & Residential Clients",
          category: "IT & Network Solutions",
          date: "Ongoing",
          location: "Morocco",
          duration: "Varies by project",
        },
      },
    },
    {
      id: 5,
      image: "/assets/img/services/renewable-energy.jpg",
      category: "Renewable Energy",
      title: "Renewable Energy Solutions",
      link: "renewable-energy",
      description: "Design and implementation of renewable energy systems.",
      details: {
        images: [
            "/assets/img/project/005.png",
          "/assets/img/project/002.png",
                "/assets/img/project/001.JPG",
                "/assets/img/project/003.png",
                "/assets/img/project/004.png",
                "/assets/img/project/006.png",
                "/assets/img/project/007.jpg",
                "/assets/img/project/008.JPG",
                "/assets/img/project/009.jpg",
        ],
        overview: "Introduction to Renewable Energy Solutions",
        content: "We offer sustainable energy solutions, including solar power systems and energy-efficient technologies, to help clients reduce their carbon footprint.",
        information: {
          client: "Industrial & Residential Clients",
          category: "Renewable Energy",
          date: "Ongoing",
          location: "Morocco",
          duration: "Varies by project",
        },
      },
    },
    {
      id: 6,
      image: "/assets/img/services/maintenance.jpg",
      category: "Maintenance & Support",
      title: "Maintenance & After-Sales Service (S.A.V.)",
      link: "maintenance",
      description: "Ongoing maintenance and support for electrical and security systems.",
      details: {
        images: [
            "/assets/img/project/006.png",
         "/assets/img/project/002.png",
                "/assets/img/project/001.JPG",
                "/assets/img/project/003.png",
                "/assets/img/project/004.png",
                "/assets/img/project/005.png",
                "/assets/img/project/007.jpg",
                "/assets/img/project/008.JPG",
                "/assets/img/project/009.jpg",
        ],
        overview: "Introduction to Maintenance & Support Services",
        content: "Our maintenance and after-sales services ensure the longevity and optimal performance of your electrical and security systems.",
        information: {
          client: "All Clients",
          category: "Maintenance & Support",
          date: "Ongoing",
          location: "Morocco",
          duration: "Varies by project",
        },
      },
    },
  ];