export const projects = [
    {
      id: 1,
      image: "/assets/img/project/05.jpg",
      category: "Product Design",
      title: "Business Task Management Dashboard Design",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
            "/assets/img/project/002.png",
            "/assets/img/project/001.JPG",
          "/assets/img/project/003.png",
          "/assets/img/project/004.png",
          "/assets/img/project/005.png",
          "/assets/img/project/006.png",
          "/assets/img/project/007.jpg",
          "/assets/img/project/008.JPG",
          "/assets/img/project/009.jpg",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
    {
      id: 2,
      image: "/assets/img/project/06.jpg",
      category: "Website Design",
      title: "Business Consulting Web Explorations Design",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
            "/assets/img/project/003.png",
          "/assets/img/project/001.JPG",
          "/assets/img/project/002.png",
          "/assets/img/project/004.png",
          "/assets/img/project/005.png",
          "/assets/img/project/006.png",
          "/assets/img/project/007.jpg",
          "/assets/img/project/008.JPG",
          "/assets/img/project/009.jpg",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
    {
      id: 3,
      image: "/assets/img/project/07.jpg",
      category: "Product Design",
      title: "Mobile Applications Design",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
            "/assets/img/project/004.png",
          "/assets/img/project/001.JPG",
          "/assets/img/project/002.png",
          "/assets/img/project/003.png",
          "/assets/img/project/005.png",
          "/assets/img/project/006.png",
          "/assets/img/project/007.jpg",
          "/assets/img/project/008.JPG",
          "/assets/img/project/009.jpg",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
    {
      id: 4,
      image: "/assets/img/project/08.jpg",
      category: "Website Design",
      title: "Furniture Website Design",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
            "/assets/img/project/005.png",
          "/assets/img/project/001.JPG",
          "/assets/img/project/002.png",
          "/assets/img/project/003.png",
          "/assets/img/project/004.png",
          "/assets/img/project/006.png",
          "/assets/img/project/007.jpg",
          "/assets/img/project/008.JPG",
          "/assets/img/project/009.jpg",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
    {
      id: 5,
      image: "/assets/img/project/09.jpg",
      category: "Product Design",
      title: "Business Card Design and Branding Identity",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
            "/assets/img/project/006.png",
          "/assets/img/project/001.JPG",
          "/assets/img/project/002.png",
          "/assets/img/project/003.png",
          "/assets/img/project/004.png",
          "/assets/img/project/005.png",
          "/assets/img/project/007.jpg",
          "/assets/img/project/008.JPG",
          "/assets/img/project/009.jpg",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
    {
      id: 6,
      image: "/assets/img/project/10.jpg",
      category: "Website Design",
      title: "Modern T-Shirt Design and Branding Identity",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
            "/assets/img/project/007.jpg",
          "/assets/img/project/001.JPG",
          "/assets/img/project/002.png",
          "/assets/img/project/003.png",
          "/assets/img/project/004.png",
          "/assets/img/project/005.png",
          "/assets/img/project/006.png",
          "/assets/img/project/008.JPG",
          "/assets/img/project/009.jpg",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
    {
      id: 7,
      image: "/assets/img/project/11.jpg",
      category: "Product Design",
      title: "Mobile Applications Design",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
            "/assets/img/project/008.JPG",
          "/assets/img/project/001.JPG",
          "/assets/img/project/002.png",
          "/assets/img/project/003.png",
          "/assets/img/project/004.png",
          "/assets/img/project/005.png",
          "/assets/img/project/006.png",
          "/assets/img/project/007.jpg",
          "/assets/img/project/009.jpg",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
    {
      id: 8,
      image: "/assets/img/project/12.jpg",
      category: "Product Design",
      title: "Furniture Website Design",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
            "/assets/img/project/009.jpg",
          "/assets/img/project/001.JPG",
          "/assets/img/project/002.png",
          "/assets/img/project/003.png",
          "/assets/img/project/004.png",
          "/assets/img/project/005.png",
          "/assets/img/project/006.png",
          "/assets/img/project/007.jpg",
          "/assets/img/project/008.JPG",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
    {
      id: 9,
      image: "/assets/img/project/12.jpg",
      category: "Product Design",
      title: "Furniture Website Design",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
         "/assets/img/project/001.JPG",
          "/assets/img/project/002.png",
          "/assets/img/project/003.png",
          "/assets/img/project/004.png",
          "/assets/img/project/005.png",
          "/assets/img/project/006.png",
          "/assets/img/project/007.jpg",
          "/assets/img/project/008.JPG",
          "/assets/img/project/009.jpg",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
    {
      id: 10,
      image: "/assets/img/project/12.jpg",
      category: "Product Design",
      title: "Furniture Website Design",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
            "/assets/img/project/002.png",
          "/assets/img/project/001.JPG",
          "/assets/img/project/003.png",
          "/assets/img/project/004.png",
          "/assets/img/project/005.png",
          "/assets/img/project/006.png",
          "/assets/img/project/007.jpg",
          "/assets/img/project/008.JPG",
          "/assets/img/project/009.jpg",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
    {
      id: 11,
      image: "/assets/img/project/12.jpg",
      category: "Product Design",
      title: "Furniture Website Design",
      link: "project-details",
      description: "Designing a dashboard for task management.",
      details: {
        images: [
            "/assets/img/project/003.png",
          "/assets/img/project/001.JPG",
          "/assets/img/project/002.png",
          "/assets/img/project/004.png",
          "/assets/img/project/005.png",
          "/assets/img/project/006.png",
          "/assets/img/project/007.jpg",
          "/assets/img/project/008.JPG",
          "/assets/img/project/009.jpg",
        ],
        overview: "Introduction Of Projects Overview",
        content: "Designing a digital product and branding project involves several key steps...",
        information: {
          client: "Myron S.",
          category: "Design & Dev",
          date: "October, 2024",
          location: "New York",
          duration: "1 month",
        },
      },
    },
  ];